#!/bin/sh
# postinst script for redis
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "${1}" in
    configure)
    [ -f /etc/default/mosquitto ] && . /etc/default/mosquitto
    [ -z "${MOSQUITTO_USER}" ] && MOSQUITTO_USER="mosquitto"
    [ -z "${MOSQUITTO_GROUP}" ] && MOSQUITTO_GROUP="mosquitto"
    if ! getent group "${MOSQUITTO_GROUP}" > /dev/null 2>&1 ; then
        addgroup --system "${MOSQUITTO_GROUP}" --quiet
    fi
    if ! id ${MOSQUITTO_USER} > /dev/null 2>&1 ; then
        adduser --system --home /var/lib/mosquitto --no-create-home \
        --ingroup "${MOSQUITTO_GROUP}" --disabled-password --shell /bin/false \
        "${MOSQUITTO_USER}"
    fi

    # Set user permissions on /var/log/redis/redis-server.log
    [ -z "${LOG_DIR}" ] && LOG_DIR="/var/log/mosquitto"
    mkdir -p "${LOG_DIR}"
    chown -R "${MOSQUITTO_USER}:${MOSQUITTO_GROUP}" "${LOG_DIR}"
    chmod 755 "${LOG_DIR}"

    # configuration files should not be modifiable by redis user, as this can be a security issue
    [ -z "${CONF_DIR}" ] && CONF_DIR="/etc/mosquitto"
    chown -Rh 'root:root' "${CONF_DIR}"
    chmod 755 "${CONF_DIR}"/*
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "${0} called with unknown argument \`${1}'" >&2
        exit 1
    ;;
esac

exit 0